services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: movie-ticket-backend:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/pbl6
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_SA_KEY=${GCP_SA_KEY}
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    networks:
      - movie-ticket-network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=pbl6
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - movie-ticket-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - movie-ticket-network

networks:
  movie-ticket-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: