version: "3.8"

networks:
  movie_app_net:
    external: true   # join vào network có sẵn

services:
  backend:
    build: .
    container_name: movie-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - movie_app_net
