#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running ESLint..."
yarn eslint "src/**/*.ts" --fix

echo "🎨 Running Prettier..."
yarn prettier --write "src/**/*.ts"

echo "✅ Pre-commit checks passed!"
