export enum BookingStatus {
  PENDING = 'PENDING',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED = 'CONFIRMED'
  // PAYMENT_FAILED = 'PAYMENT_FAILED',
  // CANCELLED = 'CANCELLED',
  // EXPIRED = 'EXPIRED'
}
